version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_fastapi_tareas
    restart: always

    environment:
      POSTGRES_DB: tareas_db
      POSTGRES_USER: tareas_user
      POSTGRES_PASSWORD: tareas_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
